name: weather
description: A weather app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  weather_icons: ^3.0.0
  google_fonts: ^5.1.0
  geolocator: ^10.0.0
  fl_chart: ^0.63.0
  sliding_up_panel: ^2.0.0+1
  shimmer: ^3.0.0
  lottie: ^2.6.0
  flutter_animate: ^4.2.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
